### 测试 count 接口
GET http://localhost:8081/user/count

### 注册接口
POST http://localhost:8081/user/register
Content-Type: application/x-www-form-urlencoded

mobile = 1512312312

### 注册接口 - 手机号不能为空 @NotBlank
POST http://localhost:8081/user/register
Content-Type: application/json

{
  "mobile": ""
}


### 注册接口 - 手机号长度校验
POST http://localhost:8081/user/register
Content-Type: application/json

{
  "mobile": "123456789101"
}


### 注册接口 - @Pattern(regexp = "^1[3-9]\\d{9}$", message = "手机号格式不正确")
POST http://localhost:8081/user/register
Content-Type: application/json

{
  "mobile": "12345678910"
}



### 发送短信验证码
POST http://localhost:8081/user/send-code
Content-Type: application/json

{
  "mobile": "18012345678"
}


### 登录
POST http://localhost:8081/user/login
Content-Type: application/json

{
  "mobile": "15359311473",
  "code" : "6666"
}
