### 测试 count 接口
GET http://localhost:8081/user/count

### 注册接口
POST http://localhost:8081/user/register
Content-Type: application/x-www-form-urlencoded

mobile = 1512312312

### 注册接口
POST http://localhost:8081/user/register
Content-Type: application/x-www-form-urlencoded

mobile =