spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user
          predicates:
            - Path=/u/**
          filters:
            - StripPrefix=1
          uri: http://127.0.0.1:8081
        - id: demo
          predicates:
            - Path=/d/**
          filters:
            - StripPrefix=1
          uri: http://127.0.0.1:8080